export const QUEUE_NAMES={
    TEST:'TEST_QUEUE',
    INGEST_REPO: 'INGEST_REPO',
    BUILD_GRAPH: 'BUILD_GRAPH',
    ANALYZE_REPO: 'ANALYZE_REPO',
    CREATE_PLAN: 'CREATE_PLAN',
    APPLY_PLAN: 'APPLY_PLAN',
    VERIFY_RUN: 'VERIFY_RUN',
    DIFF_RUN: 'DIFF_RUN',
    VERIFY_ARTIFACTS: 'VERIFY_ARTIFACTS',
} as const;


